# Translations template for swift.
# Copyright (C) 2015 ORGANIZATION
# This file is distributed under the same license as the swift project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2015.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: swift 2.3.0rc1.post7\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2015-04-16 06:06+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"

#: swift/account/auditor.py:59
#, python-format
msgid ""
"Since %(time)s: Account audits: %(passed)s passed audit,%(failed)s failed"
" audit"
msgstr ""

#: swift/account/auditor.py:82
msgid "Begin account audit pass."
msgstr ""

#: swift/account/auditor.py:88 swift/container/auditor.py:86
msgid "ERROR auditing"
msgstr ""

#: swift/account/auditor.py:93
#, python-format
msgid "Account audit pass completed: %.02fs"
msgstr ""

#: swift/account/auditor.py:99
msgid "Begin account audit \"once\" mode"
msgstr ""

#: swift/account/auditor.py:104
#, python-format
msgid "Account audit \"once\" mode completed: %.02fs"
msgstr ""

#: swift/account/auditor.py:123
#, python-format
msgid ""
"The total %(key)s for the container (%(total)s) does not match the sum of"
" %(key)s across policies (%(sum)s)"
msgstr ""

#: swift/account/auditor.py:149
#, python-format
msgid "Audit Failed for %s: %s"
msgstr ""

#: swift/account/auditor.py:153
#, python-format
msgid "ERROR Could not get account info %s"
msgstr ""

#: swift/account/reaper.py:134 swift/common/utils.py:2127
#: swift/obj/diskfile.py:476 swift/obj/updater.py:88 swift/obj/updater.py:131
#, python-format
msgid "Skipping %s as it is not mounted"
msgstr ""

#: swift/account/reaper.py:138
msgid "Exception in top-level account reaper loop"
msgstr ""

#: swift/account/reaper.py:141
#, python-format
msgid "Devices pass completed: %.02fs"
msgstr ""

#: swift/account/reaper.py:238
#, python-format
msgid "Beginning pass on account %s"
msgstr ""

#: swift/account/reaper.py:255
#, python-format
msgid "Exception with containers for account %s"
msgstr ""

#: swift/account/reaper.py:262
#, python-format
msgid "Exception with account %s"
msgstr ""

#: swift/account/reaper.py:263
#, python-format
msgid "Incomplete pass on account %s"
msgstr ""

#: swift/account/reaper.py:265
#, python-format
msgid ", %s containers deleted"
msgstr ""

#: swift/account/reaper.py:267
#, python-format
msgid ", %s objects deleted"
msgstr ""

#: swift/account/reaper.py:269
#, python-format
msgid ", %s containers remaining"
msgstr ""

#: swift/account/reaper.py:272
#, python-format
msgid ", %s objects remaining"
msgstr ""

#: swift/account/reaper.py:274
#, python-format
msgid ", %s containers possibly remaining"
msgstr ""

#: swift/account/reaper.py:277
#, python-format
msgid ", %s objects possibly remaining"
msgstr ""

#: swift/account/reaper.py:280
msgid ", return codes: "
msgstr ""

#: swift/account/reaper.py:284
#, python-format
msgid ", elapsed: %.02fs"
msgstr ""

#: swift/account/reaper.py:290
#, python-format
msgid "Account %s has not been reaped since %s"
msgstr ""

#: swift/account/reaper.py:349 swift/account/reaper.py:397
#: swift/account/reaper.py:464 swift/container/updater.py:306
#, python-format
msgid "Exception with %(ip)s:%(port)s/%(device)s"
msgstr ""

#: swift/account/reaper.py:369
#, python-format
msgid "Exception with objects for container %(container)s for account %(account)s"
msgstr ""

#: swift/account/server.py:275 swift/container/server.py:582
#: swift/obj/server.py:910
#, python-format
msgid "ERROR __call__ error with %(method)s %(path)s "
msgstr ""

#: swift/common/bufferedhttp.py:157
#, python-format
msgid "Error encoding to UTF-8: %s"
msgstr ""

#: swift/common/container_sync_realms.py:59
#: swift/common/container_sync_realms.py:68
#, python-format
msgid "Could not load %r: %s"
msgstr ""

#: swift/common/container_sync_realms.py:81
#, python-format
msgid "Error in %r with mtime_check_interval: %s"
msgstr ""

#: swift/common/db.py:347
#, python-format
msgid "Quarantined %s to %s due to %s database"
msgstr ""

#: swift/common/db.py:402
msgid "Broker error trying to rollback locked connection"
msgstr ""

#: swift/common/db.py:605
#, python-format
msgid "Invalid pending entry %(file)s: %(entry)s"
msgstr ""

#: swift/common/db_replicator.py:143
#, python-format
msgid "ERROR reading HTTP response from %s"
msgstr ""

#: swift/common/db_replicator.py:193
#, python-format
msgid "Attempted to replicate %(count)d dbs in %(time).5f seconds (%(rate).5f/s)"
msgstr ""

#: swift/common/db_replicator.py:199
#, python-format
msgid "Removed %(remove)d dbs"
msgstr ""

#: swift/common/db_replicator.py:200
#, python-format
msgid "%(success)s successes, %(failure)s failures"
msgstr ""

#: swift/common/db_replicator.py:231
#, python-format
msgid "ERROR rsync failed with %(code)s: %(args)s"
msgstr ""

#: swift/common/db_replicator.py:294
#, python-format
msgid "ERROR Bad response %(status)s from %(host)s"
msgstr ""

#: swift/common/db_replicator.py:453 swift/common/db_replicator.py:678
#, python-format
msgid "Quarantining DB %s"
msgstr ""

#: swift/common/db_replicator.py:456
#, python-format
msgid "ERROR reading db %s"
msgstr ""

#: swift/common/db_replicator.py:487
#, python-format
msgid "ERROR Remote drive not mounted %s"
msgstr ""

#: swift/common/db_replicator.py:489
#, python-format
msgid "ERROR syncing %(file)s with node %(node)s"
msgstr ""

#: swift/common/db_replicator.py:517
#, python-format
msgid "ERROR while trying to clean up %s"
msgstr ""

#: swift/common/db_replicator.py:543
msgid "ERROR Failed to get my own IPs?"
msgstr ""

#: swift/common/db_replicator.py:553
#, python-format
msgid "Skipping %(device)s as it is not mounted"
msgstr ""

#: swift/common/db_replicator.py:562
msgid "Beginning replication run"
msgstr ""

#: swift/common/db_replicator.py:567
msgid "Replication run OVER"
msgstr ""

#: swift/common/db_replicator.py:580
msgid "ERROR trying to replicate"
msgstr ""

#: swift/common/internal_client.py:193
#, python-format
msgid "Unexpected response: %s"
msgstr ""

#: swift/common/manager.py:63
msgid "WARNING: Unable to modify file descriptor limit.  Running as non-root?"
msgstr ""

#: swift/common/manager.py:70
msgid "WARNING: Unable to modify memory limit.  Running as non-root?"
msgstr ""

#: swift/common/manager.py:77
msgid "WARNING: Unable to modify max process limit.  Running as non-root?"
msgstr ""

#: swift/common/manager.py:195
msgid ""
"\n"
"user quit"
msgstr ""

#: swift/common/manager.py:232 swift/common/manager.py:547
#, python-format
msgid "No %s running"
msgstr ""

#: swift/common/manager.py:245
#, python-format
msgid "%s (%s) appears to have stopped"
msgstr ""

#: swift/common/manager.py:255
#, python-format
msgid "Waited %s seconds for %s to die; giving up"
msgstr ""

#: swift/common/manager.py:439
#, python-format
msgid "Unable to locate config number %s for %s"
msgstr ""

#: swift/common/manager.py:442
#, python-format
msgid "Unable to locate config for %s"
msgstr ""

#: swift/common/manager.py:445
msgid "Found configs:"
msgstr ""

#: swift/common/manager.py:489
#, python-format
msgid "Signal %s  pid: %s  signal: %s"
msgstr ""

#: swift/common/manager.py:496
#, python-format
msgid "Removing stale pid file %s"
msgstr ""

#: swift/common/manager.py:499
#, python-format
msgid "No permission to signal PID %d"
msgstr ""

#: swift/common/manager.py:544
#, python-format
msgid "%s #%d not running (%s)"
msgstr ""

#: swift/common/manager.py:551 swift/common/manager.py:644
#: swift/common/manager.py:647
#, python-format
msgid "%s running (%s - %s)"
msgstr ""

#: swift/common/manager.py:650
#, python-format
msgid "%s already started..."
msgstr ""

#: swift/common/manager.py:659
#, python-format
msgid "Running %s once"
msgstr ""

#: swift/common/manager.py:661
#, python-format
msgid "Starting %s"
msgstr ""

#: swift/common/manager.py:668
#, python-format
msgid "%s does not exist"
msgstr ""

#: swift/common/memcached.py:191
#, python-format
msgid "Timeout %(action)s to memcached: %(server)s"
msgstr ""

#: swift/common/memcached.py:194
#, python-format
msgid "Error %(action)s to memcached: %(server)s"
msgstr ""

#: swift/common/memcached.py:219
#, python-format
msgid "Error limiting server %s"
msgstr ""

#: swift/common/request_helpers.py:102
#, python-format
msgid "No policy with index %s"
msgstr ""

#: swift/common/request_helpers.py:395
msgid "ERROR: An error occurred while retrieving segments"
msgstr ""

#: swift/common/utils.py:388
#, python-format
msgid "Unable to locate %s in libc.  Leaving as a no-op."
msgstr ""

#: swift/common/utils.py:578
msgid "Unable to locate fallocate, posix_fallocate in libc.  Leaving as a no-op."
msgstr ""

#: swift/common/utils.py:662
#, python-format
msgid "Unable to perform fsync() on directory %s: %s"
msgstr ""

#: swift/common/utils.py:1074
#, python-format
msgid "%s: Connection reset by peer"
msgstr ""

#: swift/common/utils.py:1076 swift/common/utils.py:1079
#, python-format
msgid "%s: %s"
msgstr ""

#: swift/common/utils.py:1314
msgid "Connection refused"
msgstr ""

#: swift/common/utils.py:1316
msgid "Host unreachable"
msgstr ""

#: swift/common/utils.py:1318
msgid "Connection timeout"
msgstr ""

#: swift/common/utils.py:1620
msgid "UNCAUGHT EXCEPTION"
msgstr ""

#: swift/common/utils.py:1675
msgid "Error: missing config path argument"
msgstr ""

#: swift/common/utils.py:1680
#, python-format
msgid "Error: unable to locate %s"
msgstr ""

#: swift/common/utils.py:1988
#, python-format
msgid "Unable to read config from %s"
msgstr ""

#: swift/common/utils.py:1994
#, python-format
msgid "Unable to find %s config section in %s"
msgstr ""

#: swift/common/utils.py:2353
#, python-format
msgid "Invalid X-Container-Sync-To format %r"
msgstr ""

#: swift/common/utils.py:2358
#, python-format
msgid "No realm key for %r"
msgstr ""

#: swift/common/utils.py:2362
#, python-format
msgid "No cluster endpoint for %r %r"
msgstr ""

#: swift/common/utils.py:2371
#, python-format
msgid ""
"Invalid scheme %r in X-Container-Sync-To, must be \"//\", \"http\", or "
"\"https\"."
msgstr ""

#: swift/common/utils.py:2375
msgid "Path required in X-Container-Sync-To"
msgstr ""

#: swift/common/utils.py:2378
msgid "Params, queries, and fragments not allowed in X-Container-Sync-To"
msgstr ""

#: swift/common/utils.py:2383
#, python-format
msgid "Invalid host %r in X-Container-Sync-To"
msgstr ""

#: swift/common/utils.py:2575
msgid "Exception dumping recon cache"
msgstr ""

#: swift/common/wsgi.py:197
#, python-format
msgid "Could not bind to %s:%s after trying for %s seconds"
msgstr ""

#: swift/common/wsgi.py:207
msgid ""
"WARNING: SSL should only be enabled for testing purposes. Use external "
"SSL termination for a production deployment."
msgstr ""

#: swift/common/middleware/catch_errors.py:43
msgid "Error: An error occurred"
msgstr ""

#: swift/common/middleware/cname_lookup.py:144
#, python-format
msgid "Mapped %(given_domain)s to %(found_domain)s"
msgstr ""

#: swift/common/middleware/cname_lookup.py:156
#, python-format
msgid "Following CNAME chain for  %(given_domain)s to %(found_domain)s"
msgstr ""

#: swift/common/middleware/ratelimit.py:248
#, python-format
msgid "Returning 497 because of blacklisting: %s"
msgstr ""

#: swift/common/middleware/ratelimit.py:263
#, python-format
msgid "Ratelimit sleep log: %(sleep)s for %(account)s/%(container)s/%(object)s"
msgstr ""

#: swift/common/middleware/ratelimit.py:271
#, python-format
msgid ""
"Returning 498 for %(meth)s to %(acc)s/%(cont)s/%(obj)s . Ratelimit (Max "
"Sleep) %(e)s"
msgstr ""

#: swift/common/middleware/ratelimit.py:293
msgid "Warning: Cannot ratelimit without a memcached client"
msgstr ""

#: swift/common/middleware/recon.py:80
msgid "Error reading recon cache file"
msgstr ""

#: swift/common/middleware/recon.py:82
msgid "Error parsing recon cache file"
msgstr ""

#: swift/common/middleware/recon.py:84
msgid "Error retrieving recon data"
msgstr ""

#: swift/common/middleware/recon.py:158
msgid "Error listing devices"
msgstr ""

#: swift/common/middleware/recon.py:254
msgid "Error reading ringfile"
msgstr ""

#: swift/common/middleware/recon.py:268
msgid "Error reading swift.conf"
msgstr ""

#: swift/common/middleware/xprofile.py:243
#, python-format
msgid "Error on render profiling results: %s"
msgstr ""

#: swift/common/middleware/x_profile/exceptions.py:25
#, python-format
msgid "Profiling Error: %s"
msgstr ""

#: swift/common/middleware/x_profile/html_viewer.py:306
#, python-format
msgid "method %s is not allowed."
msgstr ""

#: swift/common/middleware/x_profile/html_viewer.py:317
#, python-format
msgid "Can not load profile data from %s."
msgstr ""

#: swift/common/middleware/x_profile/html_viewer.py:369
#: swift/common/middleware/x_profile/html_viewer.py:399
msgid "no log file found"
msgstr ""

#: swift/common/middleware/x_profile/html_viewer.py:392
#, python-format
msgid "Data download error: %s"
msgstr ""

#: swift/common/middleware/x_profile/html_viewer.py:397
msgid "python-matplotlib not installed."
msgstr ""

#: swift/common/middleware/x_profile/html_viewer.py:433
#, python-format
msgid "plotting results failed due to %s"
msgstr ""

#: swift/common/middleware/x_profile/html_viewer.py:444
msgid "The file type are forbidden to access!"
msgstr ""

#: swift/common/middleware/x_profile/html_viewer.py:465
#, python-format
msgid "Can not access the file %s."
msgstr ""

#: swift/common/middleware/x_profile/profile_model.py:128
msgid "odfpy not installed."
msgstr ""

#: swift/container/auditor.py:58
#, python-format
msgid ""
"Since %(time)s: Container audits: %(pass)s passed audit, %(fail)s failed "
"audit"
msgstr ""

#: swift/container/auditor.py:80
msgid "Begin container audit pass."
msgstr ""

#: swift/container/auditor.py:91
#, python-format
msgid "Container audit pass completed: %.02fs"
msgstr ""

#: swift/container/auditor.py:97
msgid "Begin container audit \"once\" mode"
msgstr ""

#: swift/container/auditor.py:102
#, python-format
msgid "Container audit \"once\" mode completed: %.02fs"
msgstr ""

#: swift/container/auditor.py:123
#, python-format
msgid "ERROR Could not get container info %s"
msgstr ""

#: swift/container/server.py:180
#, python-format
msgid ""
"ERROR Account update failed: different  numbers of hosts and devices in "
"request: \"%s\" vs \"%s\""
msgstr ""

#: swift/container/server.py:221
#, python-format
msgid ""
"ERROR Account update failed with %(ip)s:%(port)s/%(device)s (will retry "
"later): Response %(status)s %(reason)s"
msgstr ""

#: swift/container/server.py:230
#, python-format
msgid ""
"ERROR account update failed with %(ip)s:%(port)s/%(device)s (will retry "
"later)"
msgstr ""

#: swift/container/sync.py:217
msgid ""
"Configuration option internal_client_conf_path not defined. Using default"
" configuration, See internal-client.conf-sample for options"
msgstr ""

#: swift/container/sync.py:230
#, python-format
msgid "Unable to load internal client from config: %r (%s)"
msgstr ""

#: swift/container/sync.py:264
msgid "Begin container sync \"once\" mode"
msgstr ""

#: swift/container/sync.py:276
#, python-format
msgid "Container sync \"once\" mode completed: %.02fs"
msgstr ""

#: swift/container/sync.py:284
#, python-format
msgid ""
"Since %(time)s: %(sync)s synced [%(delete)s deletes, %(put)s puts], "
"%(skip)s skipped, %(fail)s failed"
msgstr ""

#: swift/container/sync.py:337
#, python-format
msgid "ERROR %(db_file)s: %(validate_sync_to_err)s"
msgstr ""

#: swift/container/sync.py:393
#, python-format
msgid "ERROR Syncing %s"
msgstr ""

#: swift/container/sync.py:476
#, python-format
msgid "Unknown exception trying to GET: %(account)r %(container)r %(object)r"
msgstr ""

#: swift/container/sync.py:510
#, python-format
msgid "Unauth %(sync_from)r => %(sync_to)r"
msgstr ""

#: swift/container/sync.py:516
#, python-format
msgid ""
"Not found %(sync_from)r => %(sync_to)r                       - object "
"%(obj_name)r"
msgstr ""

#: swift/container/sync.py:523 swift/container/sync.py:530
#, python-format
msgid "ERROR Syncing %(db_file)s %(row)s"
msgstr ""

#: swift/container/updater.py:77
#, python-format
msgid "ERROR:  Failed to get paths to drive partitions: %s"
msgstr ""

#: swift/container/updater.py:91 swift/obj/reconstructor.py:788
#: swift/obj/replicator.py:487 swift/obj/replicator.py:575
#, python-format
msgid "%s is not mounted"
msgstr ""

#: swift/container/updater.py:110
#, python-format
msgid "ERROR with loading suppressions from %s: "
msgstr ""

#: swift/container/updater.py:120
msgid "Begin container update sweep"
msgstr ""

#: swift/container/updater.py:154
#, python-format
msgid ""
"Container update sweep of %(path)s completed: %(elapsed).02fs, "
"%(success)s successes, %(fail)s failures, %(no_change)s with no changes"
msgstr ""

#: swift/container/updater.py:168
#, python-format
msgid "Container update sweep completed: %.02fs"
msgstr ""

#: swift/container/updater.py:180
msgid "Begin container update single threaded sweep"
msgstr ""

#: swift/container/updater.py:188
#, python-format
msgid ""
"Container update single threaded sweep completed: %(elapsed).02fs, "
"%(success)s successes, %(fail)s failures, %(no_change)s with no changes"
msgstr ""

#: swift/container/updater.py:243
#, python-format
msgid "Update report sent for %(container)s %(dbfile)s"
msgstr ""

#: swift/container/updater.py:252
#, python-format
msgid "Update report failed for %(container)s %(dbfile)s"
msgstr ""

#: swift/container/updater.py:294
#, python-format
msgid ""
"ERROR account update failed with %(ip)s:%(port)s/%(device)s (will retry "
"later): "
msgstr ""

#: swift/obj/auditor.py:78
#, python-format
msgid " - parallel, %s"
msgstr ""

#: swift/obj/auditor.py:80
#, python-format
msgid " - %s"
msgstr ""

#: swift/obj/auditor.py:81
#, python-format
msgid "Begin object audit \"%s\" mode (%s%s)"
msgstr ""

#: swift/obj/auditor.py:100
#, python-format
msgid ""
"Object audit (%(type)s). Since %(start_time)s: Locally: %(passes)d "
"passed, %(quars)d quarantined, %(errors)d errors files/sec: %(frate).2f ,"
" bytes/sec: %(brate).2f, Total time: %(total).2f, Auditing time: "
"%(audit).2f, Rate: %(audit_rate).2f"
msgstr ""

#: swift/obj/auditor.py:134
#, python-format
msgid ""
"Object audit (%(type)s) \"%(mode)s\" mode completed: %(elapsed).02fs. "
"Total quarantined: %(quars)d, Total errors: %(errors)d, Total files/sec: "
"%(frate).2f, Total bytes/sec: %(brate).2f, Auditing time: %(audit).2f, "
"Rate: %(audit_rate).2f"
msgstr ""

#: swift/obj/auditor.py:149
#, python-format
msgid "Object audit stats: %s"
msgstr ""

#: swift/obj/auditor.py:177
#, python-format
msgid "ERROR Trying to audit %s"
msgstr ""

#: swift/obj/auditor.py:213
#, python-format
msgid "ERROR Object %(obj)s failed audit and was quarantined: %(err)s"
msgstr ""

#: swift/obj/auditor.py:263
#, python-format
msgid "ERROR: Unable to run auditing: %s"
msgstr ""

#: swift/obj/auditor.py:334 swift/obj/auditor.py:355
#, python-format
msgid "ERROR auditing: %s"
msgstr ""

#: swift/obj/diskfile.py:323 swift/obj/diskfile.py:2305
#, python-format
msgid "Quarantined %(hsh_path)s to %(quar_path)s because it is not a directory"
msgstr ""

#: swift/obj/diskfile.py:414 swift/obj/diskfile.py:2373
msgid "Error hashing suffix"
msgstr ""

#: swift/obj/diskfile.py:486 swift/obj/updater.py:162
#, python-format
msgid "Directory %r does not map to a valid policy (%s)"
msgstr ""

#: swift/obj/diskfile.py:737
#, python-format
msgid "Quarantined %(object_path)s to %(quar_path)s because it is not a directory"
msgstr ""

#: swift/obj/diskfile.py:936 swift/obj/diskfile.py:1795
#, python-format
msgid "Problem cleaning up %s"
msgstr ""

#: swift/obj/diskfile.py:1253
#, python-format
msgid "ERROR DiskFile %(data_file)s close failure: %(exc)s : %(stack)s"
msgstr ""

#: swift/obj/diskfile.py:1543
#, python-format
msgid ""
"Client path %(client)s does not match path stored in object metadata "
"%(meta)s"
msgstr ""

#: swift/obj/diskfile.py:1797
#, python-format
msgid "Problem fsyncing durable state file: %s"
msgstr ""

#: swift/obj/diskfile.py:1802
#, python-format
msgid "No space left on device for %s"
msgstr ""

#: swift/obj/diskfile.py:1806
#, python-format
msgid "Problem writing durable state file: %s"
msgstr ""

#: swift/obj/expirer.py:79
#, python-format
msgid "Pass completed in %ds; %d objects expired"
msgstr ""

#: swift/obj/expirer.py:86
#, python-format
msgid "Pass so far %ds; %d objects expired"
msgstr ""

#: swift/obj/expirer.py:170
#, python-format
msgid "Pass beginning; %s possible containers; %s possible objects"
msgstr ""

#: swift/obj/expirer.py:196
#, python-format
msgid "Exception while deleting container %s %s"
msgstr ""

#: swift/obj/expirer.py:201 swift/obj/expirer.py:218
msgid "Unhandled exception"
msgstr ""

#: swift/obj/expirer.py:268
#, python-format
msgid "Exception while deleting object %s %s %s"
msgstr ""

#: swift/obj/reconstructor.py:189 swift/obj/reconstructor.py:472
#, python-format
msgid "Invalid response %(resp)s from %(full_path)s"
msgstr ""

#: swift/obj/reconstructor.py:195
#, python-format
msgid "Trying to GET %(full_path)s"
msgstr ""

#: swift/obj/reconstructor.py:301
#, python-format
msgid "Error trying to rebuild %(path)s policy#%(policy)d frag#%(frag_index)s"
msgstr ""

#: swift/obj/reconstructor.py:324
#, python-format
msgid ""
"%(reconstructed)d/%(total)d (%(percentage).2f%%) partitions reconstructed"
" in %(time).2fs (%(rate).2f/sec, %(remaining)s remaining)"
msgstr ""

#: swift/obj/reconstructor.py:337 swift/obj/replicator.py:419
#, python-format
msgid ""
"%(checked)d suffixes checked - %(hashed).2f%% hashed, %(synced).2f%% "
"synced"
msgstr ""

#: swift/obj/reconstructor.py:344 swift/obj/replicator.py:426
#, python-format
msgid "Partition times: max %(max).4fs, min %(min).4fs, med %(med).4fs"
msgstr ""

#: swift/obj/reconstructor.py:352
#, python-format
msgid "Nothing reconstructed for %s seconds."
msgstr ""

#: swift/obj/reconstructor.py:381 swift/obj/replicator.py:463
msgid "Lockup detected.. killing live coros."
msgstr ""

#: swift/obj/reconstructor.py:442
#, python-format
msgid "Trying to sync suffixes with %s"
msgstr ""

#: swift/obj/reconstructor.py:467
#, python-format
msgid "%s responded as unmounted"
msgstr ""

#: swift/obj/reconstructor.py:849 swift/obj/replicator.py:295
#, python-format
msgid "Removing partition: %s"
msgstr ""

#: swift/obj/reconstructor.py:865
msgid "Ring change detected. Aborting current reconstruction pass."
msgstr ""

#: swift/obj/reconstructor.py:884
msgid "Exception in top-levelreconstruction loop"
msgstr ""

#: swift/obj/reconstructor.py:894
msgid "Running object reconstructor in script mode."
msgstr ""

#: swift/obj/reconstructor.py:903
#, python-format
msgid "Object reconstruction complete (once). (%.02f minutes)"
msgstr ""

#: swift/obj/reconstructor.py:910
msgid "Starting object reconstructor in daemon mode."
msgstr ""

#: swift/obj/reconstructor.py:914
msgid "Starting object reconstruction pass."
msgstr ""

#: swift/obj/reconstructor.py:919
#, python-format
msgid "Object reconstruction complete. (%.02f minutes)"
msgstr ""

#: swift/obj/replicator.py:139
#, python-format
msgid "Killing long-running rsync: %s"
msgstr ""

#: swift/obj/replicator.py:153
#, python-format
msgid "Bad rsync return code: %(ret)d <- %(args)s"
msgstr ""

#: swift/obj/replicator.py:160 swift/obj/replicator.py:164
#, python-format
msgid "Successful rsync of %(src)s at %(dst)s (%(time).03f)"
msgstr ""

#: swift/obj/replicator.py:281
#, python-format
msgid "Removing %s objects"
msgstr ""

#: swift/obj/replicator.py:289
msgid "Error syncing handoff partition"
msgstr ""

#: swift/obj/replicator.py:351
#, python-format
msgid "%(ip)s/%(device)s responded as unmounted"
msgstr ""

#: swift/obj/replicator.py:356
#, python-format
msgid "Invalid response %(resp)s from %(ip)s"
msgstr ""

#: swift/obj/replicator.py:391
#, python-format
msgid "Error syncing with node: %s"
msgstr ""

#: swift/obj/replicator.py:395
msgid "Error syncing partition"
msgstr ""

#: swift/obj/replicator.py:408
#, python-format
msgid ""
"%(replicated)d/%(total)d (%(percentage).2f%%) partitions replicated in "
"%(time).2fs (%(rate).2f/sec, %(remaining)s remaining)"
msgstr ""

#: swift/obj/replicator.py:434
#, python-format
msgid "Nothing replicated for %s seconds."
msgstr ""

#: swift/obj/replicator.py:578
msgid "Ring change detected. Aborting current replication pass."
msgstr ""

#: swift/obj/replicator.py:599
msgid "Exception in top-level replication loop"
msgstr ""

#: swift/obj/replicator.py:608
msgid "Running object replicator in script mode."
msgstr ""

#: swift/obj/replicator.py:626
#, python-format
msgid "Object replication complete (once). (%.02f minutes)"
msgstr ""

#: swift/obj/replicator.py:633
msgid "Starting object replicator in daemon mode."
msgstr ""

#: swift/obj/replicator.py:637
msgid "Starting object replication pass."
msgstr ""

#: swift/obj/replicator.py:642
#, python-format
msgid "Object replication complete. (%.02f minutes)"
msgstr ""

#: swift/obj/server.py:231
#, python-format
msgid ""
"ERROR Container update failed (saving for async update later): %(status)d"
" response from %(ip)s:%(port)s/%(dev)s"
msgstr ""

#: swift/obj/server.py:238
#, python-format
msgid ""
"ERROR container update failed with %(ip)s:%(port)s/%(dev)s (saving for "
"async update later)"
msgstr ""

#: swift/obj/server.py:273
#, python-format
msgid ""
"ERROR Container update failed: different numbers of hosts and devices in "
"request: \"%s\" vs \"%s\""
msgstr ""

#: swift/obj/updater.py:63
#, python-format
msgid "ERROR: Unable to access %(path)s: %(error)s"
msgstr ""

#: swift/obj/updater.py:78
msgid "Begin object update sweep"
msgstr ""

#: swift/obj/updater.py:104
#, python-format
msgid ""
"Object update sweep of %(device)s completed: %(elapsed).02fs, %(success)s"
" successes, %(fail)s failures"
msgstr ""

#: swift/obj/updater.py:113
#, python-format
msgid "Object update sweep completed: %.02fs"
msgstr ""

#: swift/obj/updater.py:122
msgid "Begin object update single threaded sweep"
msgstr ""

#: swift/obj/updater.py:136
#, python-format
msgid ""
"Object update single threaded sweep completed: %(elapsed).02fs, "
"%(success)s successes, %(fail)s failures"
msgstr ""

#: swift/obj/updater.py:179
#, python-format
msgid "ERROR async pending file with unexpected name %s"
msgstr ""

#: swift/obj/updater.py:209
#, python-format
msgid "ERROR Pickle problem, quarantining %s"
msgstr ""

#: swift/obj/updater.py:274
#, python-format
msgid "ERROR with remote server %(ip)s:%(port)s/%(device)s"
msgstr ""

#: swift/proxy/server.py:405
msgid "ERROR Unhandled exception in request"
msgstr ""

#: swift/proxy/server.py:460
#, python-format
msgid "Node error limited %(ip)s:%(port)s (%(device)s)"
msgstr ""

#: swift/proxy/server.py:477 swift/proxy/server.py:495
#, python-format
msgid "%(msg)s %(ip)s:%(port)s/%(device)s"
msgstr ""

#: swift/proxy/server.py:571
#, python-format
msgid "ERROR with %(type)s server %(ip)s:%(port)s/%(device)s re: %(info)s"
msgstr ""

#: swift/proxy/controllers/account.py:64
msgid "Account"
msgstr ""

#: swift/proxy/controllers/base.py:752 swift/proxy/controllers/base.py:814
#: swift/proxy/controllers/obj.py:364 swift/proxy/controllers/obj.py:411
#: swift/proxy/controllers/obj.py:427 swift/proxy/controllers/obj.py:643
#: swift/proxy/controllers/obj.py:1130 swift/proxy/controllers/obj.py:1591
#: swift/proxy/controllers/obj.py:1763 swift/proxy/controllers/obj.py:1908
#: swift/proxy/controllers/obj.py:2093
msgid "Object"
msgstr ""

#: swift/proxy/controllers/base.py:753
msgid "Trying to read during GET (retrying)"
msgstr ""

#: swift/proxy/controllers/base.py:815
msgid "Trying to read during GET"
msgstr ""

#: swift/proxy/controllers/base.py:819
#, python-format
msgid "Client did not read from proxy within %ss"
msgstr ""

#: swift/proxy/controllers/base.py:824
msgid "Client disconnected on read"
msgstr ""

#: swift/proxy/controllers/base.py:826
msgid "Trying to send to client"
msgstr ""

#: swift/proxy/controllers/base.py:863 swift/proxy/controllers/base.py:1141
#, python-format
msgid "Trying to %(method)s %(path)s"
msgstr ""

#: swift/proxy/controllers/base.py:902 swift/proxy/controllers/base.py:1129
#: swift/proxy/controllers/obj.py:402 swift/proxy/controllers/obj.py:450
#: swift/proxy/controllers/obj.py:1900 swift/proxy/controllers/obj.py:2138
msgid "ERROR Insufficient Storage"
msgstr ""

#: swift/proxy/controllers/base.py:905
#, python-format
msgid "ERROR %(status)d %(body)s From %(type)s Server"
msgstr ""

#: swift/proxy/controllers/base.py:1132
#, python-format
msgid "ERROR %(status)d Trying to %(method)s %(path)sFrom Container Server"
msgstr ""

#: swift/proxy/controllers/base.py:1260
#, python-format
msgid "%(type)s returning 503 for %(statuses)s"
msgstr ""

#: swift/proxy/controllers/container.py:98 swift/proxy/controllers/obj.py:161
msgid "Container"
msgstr ""

#: swift/proxy/controllers/obj.py:365 swift/proxy/controllers/obj.py:1592
#, python-format
msgid "Trying to write to %s"
msgstr ""

#: swift/proxy/controllers/obj.py:406 swift/proxy/controllers/obj.py:1903
#, python-format
msgid "ERROR %(status)d Expect: 100-continue From Object Server"
msgstr ""

#: swift/proxy/controllers/obj.py:412 swift/proxy/controllers/obj.py:1909
#, python-format
msgid "Expect: 100-continue on %s"
msgstr ""

#: swift/proxy/controllers/obj.py:428
#, python-format
msgid "Trying to get final status of PUT to %s"
msgstr ""

#: swift/proxy/controllers/obj.py:454 swift/proxy/controllers/obj.py:2143
#, python-format
msgid "ERROR %(status)d %(body)s From Object Server re: %(path)s"
msgstr ""

#: swift/proxy/controllers/obj.py:716
#, python-format
msgid "Object PUT returning 412, %(statuses)r"
msgstr ""

#: swift/proxy/controllers/obj.py:725
#, python-format
msgid "Object PUT returning 202 for 409: %(req_timestamp)s <= %(timestamps)r"
msgstr ""

#: swift/proxy/controllers/obj.py:811 swift/proxy/controllers/obj.py:2048
#, python-format
msgid "ERROR Client read timeout (%ss)"
msgstr ""

#: swift/proxy/controllers/obj.py:818 swift/proxy/controllers/obj.py:2055
msgid "ERROR Exception causing client disconnect"
msgstr ""

#: swift/proxy/controllers/obj.py:823 swift/proxy/controllers/obj.py:2060
msgid "Client disconnected without sending enough data"
msgstr ""

#: swift/proxy/controllers/obj.py:869
#, python-format
msgid "Object servers returned %s mismatched etags"
msgstr ""

#: swift/proxy/controllers/obj.py:873 swift/proxy/controllers/obj.py:2218
msgid "Object PUT"
msgstr ""

#: swift/proxy/controllers/obj.py:2035
#, python-format
msgid "Not enough object servers ack'ed (got %d)"
msgstr ""

#: swift/proxy/controllers/obj.py:2094
#, python-format
msgid "Trying to get %s status of PUT to %s"
msgstr ""

